apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox:latest
      command: ["sleep", "3600"]
      imagePullPolicy: IfNotPresent
